#!/bin/bash
# Sequentially run, one kernel at a time (no concurrency), every kernel in
# SPEC_shim_root/manifest.txt (SPEC CPU2017 C-benchmarks generated by
# scripts/gen_spec_kernels.py -- see docs/SPEC2017_STATUS.md).
# Mirrors run_remaining_polybench_tsvc_cbench.sh's structure/logging.
set -u
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SPEC_LOG="logs_spec"
mkdir -p "$SPEC_LOG"

run_one() {
  local prog="$1"
  local name; name=$(basename "$prog" .c)
  local log="$SPEC_LOG/${name}.log"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] START $name"
  python optimize.py --program "$prog" --rounds 5 --runs 3 > "$log" 2>&1
  local code=$?
  if [ $code -eq 0 ]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] DONE  $name"
  else
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] FAIL  $name (exit $code)"
  fi
}

echo "========================================"
echo "SPEC CPU2017 ($(wc -l < SPEC_shim_root/manifest.txt) kernels), sequential, rounds=5"
echo "========================================"
mapfile -t SPEC_PROGS < SPEC_shim_root/manifest.txt
for prog in "${SPEC_PROGS[@]}"; do
  [ -n "$prog" ] || continue
  run_one "$prog"
done

echo ""
echo "========================================"
echo "ALL DONE: SPEC (${#SPEC_PROGS[@]})."
echo "========================================"

printf "%-24s  %-12s  %-10s\n" "benchmark" "baseline(ms)" "best"
printf "%-24s  %-12s  %-10s\n" "---------" "------------" "----"
for prog in "${SPEC_PROGS[@]}"; do
  name=$(basename "$prog" .c)
  log="$SPEC_LOG/${name}.log"
  [ -f "$log" ] || { printf "%-24s  %-12s  %-10s\n" "$name" "-" "not run"; continue; }
  baseline=$(grep "基线 -O3:" "$log" | tail -1 | awk '{print $3}')
  best=$(grep -E "最优加速比:|组合加速比:" "$log" | tail -1 | awk '{print $2}')
  [ -z "$best" ] && best="incomplete"
  [ -z "$baseline" ] && baseline="?"
  printf "%-24s  %-12s  %-10s\n" "$name" "$baseline" "$best"
done
